"""
Bond Yield Rich/Cheap Model
============================
A Streamlit web application that uses rolling multiple linear regression
to determine if government bond yields are rich (too low vs fundamentals),
cheap (too high), or neutral.

Supports US 10Y and AU 10Y yields with dynamic variable intake.
Single Excel file with both yield columns — toggle between countries.

Author: Generated by Claude
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import io
from datetime import datetime

# ─────────────────────────────────────────────────────────────
# Page config
# ─────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Bond Yield Rich/Cheap Model",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Custom CSS
st.markdown("""
<style>
    .signal-box {
        padding: 24px; border-radius: 12px; text-align: center;
        margin-bottom: 16px; color: white; font-weight: bold;
    }
    .signal-cheap { background: linear-gradient(135deg, #c0392b, #e74c3c); }
    .signal-rich  { background: linear-gradient(135deg, #1b8a3d, #27ae60); }
    .signal-neutral { background: linear-gradient(135deg, #636e72, #95a5a6); }
    .metric-card {
        background: #f8f9fa; border-radius: 8px; padding: 16px;
        border-left: 4px solid #3498db; margin-bottom: 8px;
    }
    div[data-testid="stSidebar"] { background-color: #f0f2f6; }
</style>
""", unsafe_allow_html=True)


# ─────────────────────────────────────────────────────────────
# Constants for auto-detection
# ─────────────────────────────────────────────────────────────
DATE_ALIASES = ["date"]

# Yield column aliases per country
YIELD_ALIASES = {
    "US 10Y": [
        "us 10y yield", "us 10yr yield", "us_10y_yield", "us 10y",
        "us10y", "ust 10y", "10y yield",
    ],
    "AU 10Y": [
        "au 10y yield", "au 10yr yield", "au_10y_yield", "au 10y",
        "au10y", "acgb 10y", "australia 10y yield",
    ],
}

VALID_FLAGS = {"L", "LM", "LMP", "MP", "P", "N"}
DEFAULT_FLAG = "LM"

FLAG_DESCRIPTIONS = {
    "L": "Level",
    "LM": "Level + MoM Change",
    "LMP": "Level + MoM Change + % Change",
    "MP": "MoM Change + % Change",
    "P": "% Change",
    "N": "Excluded",
}


# ─────────────────────────────────────────────────────────────
# Data loading & feature engineering
# ─────────────────────────────────────────────────────────────
def _match_column(df_columns, aliases):
    """Fuzzy-match a DataFrame column against a list of aliases (case-insensitive)."""
    lower_cols = {}
    for c in df_columns:
        try:
            lower_cols[str(c).strip().lower()] = c
        except Exception:
            continue
    for alias in aliases:
        if alias in lower_cols:
            return lower_cols[alias]
    return None


def load_data(uploaded_file, country):
    """
    Load and validate the uploaded Excel file for a specific country's yield.

    The Excel file has two tabs:
        - 'US Model field and data' → used when country = 'US 10Y'
        - 'AU Model field and data' → used when country = 'AU 10Y'

    Each tab has the same layout:
        Row 1: Column headers (Cell A1 may contain a Bloomberg reference date — ignored)
        Row 2: Feature flags (L / LM / LMP / MP / P / N) — blank for Date and yield columns
        Row 3+: Data

    Returns:
        df: cleaned DataFrame with standardised column names
        dep_var_col: original name of the dependent variable column
        variable_flags: dict mapping {internal_col_name: flag} for independent variables
        original_names: dict mapping {internal_col_name: original_col_name} for display
    """
    # Map country to tab name
    tab_names = {
        "US 10Y": "US Model field and data",
        "AU 10Y": "AU Model field and data",
    }
    sheet_name = tab_names[country]

    try:
        raw = pd.read_excel(uploaded_file, sheet_name=sheet_name, header=None)
    except ValueError:
        # Tab not found — show available tabs
        try:
            xls = pd.ExcelFile(uploaded_file)
            available = ", ".join(f"'{s}'" for s in xls.sheet_names)
        except Exception:
            available = "(could not read file)"
        st.error(f"❌ Could not find tab '{sheet_name}'. Available tabs: {available}")
        return None, None, None, None
    except Exception as e:
        st.error(f"❌ Could not read Excel file: {e}")
        return None, None, None, None

    if len(raw) < 3:
        st.error(f"❌ Tab '{sheet_name}' must have at least 3 rows: headers (row 1), flags (row 2), and data (row 3+).")
        return None, None, None, None

    # Extract headers and flag row
    headers = [str(h).strip() for h in raw.iloc[0]]
    flag_row = [str(f).strip().upper() for f in raw.iloc[1]]

    # Build DataFrame from data rows (row index 2 onward)
    df = raw.iloc[2:].reset_index(drop=True)
    df.columns = headers

    # --- Auto-detect Date column ---
    date_col = _match_column(headers, DATE_ALIASES)
    if date_col is None:
        for h in headers:
            try:
                test = pd.to_datetime(df[h], errors="coerce")
                if test.notna().sum() > len(df) * 0.5:
                    date_col = h
                    break
            except Exception:
                continue
    if date_col is None:
        st.error(f"❌ Could not find a Date column on tab '{sheet_name}'.")
        return None, None, None, None

    # --- Auto-detect yield (dependent variable) ---
    dep_var_col = _match_column(headers, YIELD_ALIASES[country])
    if dep_var_col is None:
        st.error(f"❌ Could not find the {country} Yield column on tab '{sheet_name}'. "
                 f"Expected one of: " + ", ".join(f"'{a}'" for a in YIELD_ALIASES[country]))
        return None, None, None, None

    # --- Parse flags for all other columns ---
    header_to_idx = {h: i for i, h in enumerate(headers)}
    variable_flags = {}
    original_names = {}

    skip_cols = {date_col, dep_var_col}
    unrecognised_flags = []

    for col_name in headers:
        if col_name in skip_cols:
            continue
        idx = header_to_idx[col_name]
        raw_flag = flag_row[idx] if idx < len(flag_row) else ""

        if col_name.lower() in ("", "nan", "none"):
            continue

        # Parse flag
        if raw_flag in VALID_FLAGS:
            flag = raw_flag
        elif raw_flag in ("", "NAN", "NONE", "NAT"):
            flag = DEFAULT_FLAG
        else:
            unrecognised_flags.append((col_name, raw_flag))
            flag = DEFAULT_FLAG

        internal = col_name.strip().lower().replace(" ", "_").replace("&", "and")
        internal = "".join(c if c.isalnum() or c == "_" else "_" for c in internal)

        variable_flags[internal] = flag
        original_names[internal] = col_name

    if unrecognised_flags:
        flag_list = ", ".join(f"'{col}' → '{f}'" for col, f in unrecognised_flags)
        st.warning(f"⚠️ Unrecognised flags (defaulting to {DEFAULT_FLAG}): {flag_list}. "
                   f"Valid flags: {', '.join(sorted(VALID_FLAGS))}")

    active_vars = {k: v for k, v in variable_flags.items() if v != "N"}
    if not active_vars:
        st.error("❌ All independent variables are flagged 'N' (excluded). At least one must be included.")
        return None, None, None, None

    # --- Build clean DataFrame ---
    rename_map = {date_col: "date", dep_var_col: "bond_yield"}
    for internal, orig in original_names.items():
        rename_map[orig] = internal

    df = df.rename(columns=rename_map)

    keep_cols = ["date", "bond_yield"] + list(original_names.keys())
    keep_cols = [c for c in keep_cols if c in df.columns]
    df = df[keep_cols].copy()

    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    for c in df.columns:
        if c != "date":
            df[c] = pd.to_numeric(df[c], errors="coerce")

    df = df.dropna(subset=["date"]).sort_values("date").reset_index(drop=True)
    df = df.ffill()

    return df, dep_var_col, variable_flags, original_names


def engineer_features(df, variable_flags, original_names, change_on_change=False):
    """
    Create derived features based on each variable's flag.

    Flags:
        L   → level only
        LM  → level + monthly change
        LMP → level + monthly change + % change
        MP  → monthly change + % change
        P   → % change only
        N   → excluded

    If change_on_change=True:
        - Dependent variable becomes ΔYield (monthly change)
        - All "Level" terms are dropped
        - Variables flagged "L" are promoted to MoM change

    Returns:
        feat_df, feature_cols, feature_labels, competing_pairs
    """
    feat = df[["date", "bond_yield"]].copy()

    if change_on_change:
        feat["bond_yield_level"] = feat["bond_yield"].copy()
        feat["bond_yield"] = feat["bond_yield"].diff()

    feature_cols = []
    feature_labels = {}
    competing_pairs = []

    for var, flag in variable_flags.items():
        if flag == "N":
            continue
        if var not in df.columns:
            continue

        display_name = original_names.get(var, var)

        if change_on_change:
            has_pct = "P" in flag

            col_name = f"{var}_change"
            feat[col_name] = df[var].diff()
            feature_cols.append(col_name)
            feature_labels[col_name] = f"{display_name} MoM Chg"

            if has_pct:
                col_name_p = f"{var}_pct_change"
                feat[col_name_p] = df[var].pct_change() * 100
                feature_cols.append(col_name_p)
                feature_labels[col_name_p] = f"{display_name} % Chg"
                competing_pairs.append((f"{var}_change", f"{var}_pct_change", var))
        else:
            if "L" in flag:
                col_name = f"{var}_level"
                feat[col_name] = df[var]
                feature_cols.append(col_name)
                feature_labels[col_name] = f"{display_name} Level"

            has_mom = "M" in flag
            has_pct = "P" in flag

            if has_mom:
                col_name = f"{var}_change"
                feat[col_name] = df[var].diff()
                feature_cols.append(col_name)
                feature_labels[col_name] = f"{display_name} MoM Change"

            if has_pct:
                col_name = f"{var}_pct_change"
                feat[col_name] = df[var].pct_change() * 100
                feature_cols.append(col_name)
                feature_labels[col_name] = f"{display_name} % Change"

            if has_mom and has_pct:
                competing_pairs.append((f"{var}_change", f"{var}_pct_change", var))

    feat = feat.dropna().reset_index(drop=True)
    feat = feat.replace([np.inf, -np.inf], np.nan).dropna().reset_index(drop=True)

    return feat, feature_cols, feature_labels, competing_pairs


# ─────────────────────────────────────────────────────────────
# Regression engine
# ─────────────────────────────────────────────────────────────
def run_regression(feat_df, feature_cols, lookback, competing_pairs=None):
    """
    Run rolling-window OLS regression with per-window feature selection.

    Uses StandardScaler + QR decomposition for numerical stability.
    Coefficients and standard errors are unscaled back to natural units.

    Returns:
        results, model_stats, coef_df, latest_selections, active_feature_cols
    """
    from scipy import stats as sp_stats

    if competing_pairs is None:
        competing_pairs = []

    n = len(feat_df)
    if n < lookback + 1:
        st.error(f"Not enough data ({n} rows) for a {lookback}-month lookback window.")
        return None

    X_all = feat_df[feature_cols].values
    y_all = feat_df["bond_yield"].values
    col_index = {c: i for i, c in enumerate(feature_cols)}

    competing_mom_cols = {mom for mom, pct, var in competing_pairs}
    competing_pct_cols = {pct for mom, pct, var in competing_pairs}
    base_col_indices = [col_index[c] for c in feature_cols
                        if c not in competing_mom_cols and c not in competing_pct_cols]

    predictions = np.full(n, np.nan)
    residuals = np.full(n, np.nan)
    coef_history = []
    latest_selections = {}
    active_feature_cols = None

    for i in range(lookback, n):
        y_train = y_all[i - lookback:i]

        window_col_indices = list(base_col_indices)
        window_selections = {}
        window_feature_names = [feature_cols[idx] for idx in base_col_indices]

        for mom_col, pct_col, var in competing_pairs:
            mom_idx = col_index[mom_col]
            pct_idx = col_index[pct_col]
            mom_vals = X_all[i - lookback:i, mom_idx]
            pct_vals = X_all[i - lookback:i, pct_idx]

            valid = ~(np.isnan(mom_vals) | np.isnan(pct_vals) | np.isnan(y_train))
            if valid.sum() < 10:
                window_col_indices.append(mom_idx)
                window_feature_names.append(mom_col)
                window_selections[var] = "mom"
                continue

            mom_corr = abs(np.corrcoef(mom_vals[valid], y_train[valid])[0, 1])
            pct_corr = abs(np.corrcoef(pct_vals[valid], y_train[valid])[0, 1])

            if np.isnan(mom_corr):
                mom_corr = 0.0
            if np.isnan(pct_corr):
                pct_corr = 0.0

            if pct_corr > mom_corr:
                window_col_indices.append(pct_idx)
                window_feature_names.append(pct_col)
                window_selections[var] = "pct"
            else:
                window_col_indices.append(mom_idx)
                window_feature_names.append(mom_col)
                window_selections[var] = "mom"

        X_train = X_all[i - lookback:i][:, window_col_indices]

        mask = ~(np.isnan(X_train).any(axis=1) | np.isnan(y_train))
        if mask.sum() < 20:
            continue

        model = LinearRegression()
        model.fit(X_train[mask], y_train[mask])

        X_pred = X_all[i:i+1][:, window_col_indices]
        pred = model.predict(X_pred)[0]
        predictions[i] = pred
        residuals[i] = y_all[i] - pred
        coef_history.append({
            "idx": i,
            "date": feat_df["date"].iloc[i],
            "intercept": model.intercept_,
            **{f"coef_{c}": v for c, v in zip(window_feature_names, model.coef_)},
        })

        latest_selections = window_selections
        active_feature_cols = window_feature_names

    results = feat_df.copy()
    results["predicted"] = predictions
    results["residual"] = residuals

    if active_feature_cols is None:
        st.error("Regression could not produce results for any window.")
        return None

    # ══════════════════════════════════════════════════════════════
    # Final-window statistics with QR decomposition + StandardScaler
    # ══════════════════════════════════════════════════════════════
    last_start = n - lookback
    y_last = y_all[last_start:n]

    final_col_indices = list(base_col_indices)
    final_feature_names = [feature_cols[idx] for idx in base_col_indices]
    for mom_col, pct_col, var in competing_pairs:
        mom_idx = col_index[mom_col]
        pct_idx = col_index[pct_col]
        if latest_selections.get(var) == "pct":
            final_col_indices.append(pct_idx)
            final_feature_names.append(pct_col)
        else:
            final_col_indices.append(mom_idx)
            final_feature_names.append(mom_col)

    X_last_raw = X_all[last_start:n][:, final_col_indices]
    mask = ~(np.isnan(X_last_raw).any(axis=1) | np.isnan(y_last))
    X_clean = X_last_raw[mask]
    y_clean = y_last[mask]

    n_obs = X_clean.shape[0]
    k = X_clean.shape[1]
    dof = n_obs - k - 1

    raw_std = np.std(X_clean, axis=0, ddof=0)
    valid_feat_mask = raw_std > 1e-12
    if not valid_feat_mask.all():
        X_clean = X_clean[:, valid_feat_mask]
        final_feature_names = [f for f, v in zip(final_feature_names, valid_feat_mask) if v]
        final_col_indices = [idx for idx, v in zip(final_col_indices, valid_feat_mask) if v]
        k = X_clean.shape[1]
        dof = n_obs - k - 1

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_clean)
    x_std = scaler.scale_
    x_mean = scaler.mean_

    X_scaled = np.nan_to_num(X_scaled, nan=0.0)

    X_design = np.column_stack([np.ones(n_obs), X_scaled])

    Q, R = np.linalg.qr(X_design, mode='reduced')

    Qty = Q.T @ y_clean
    try:
        from scipy.linalg import solve_triangular
        beta_scaled = solve_triangular(R, Qty)
    except (np.linalg.LinAlgError, Exception):
        beta_scaled, _, _, _ = np.linalg.lstsq(X_design, y_clean, rcond=None)

    intercept_scaled = beta_scaled[0]
    coefs_scaled = beta_scaled[1:]

    y_pred_last = X_design @ beta_scaled
    resid = y_clean - y_pred_last
    ss_res = np.sum(resid ** 2)
    ss_tot = np.sum((y_clean - y_clean.mean()) ** 2)
    r2 = 1 - ss_res / ss_tot
    adj_r2 = 1 - (1 - r2) * (n_obs - 1) / max(dof, 1)
    sigma2 = ss_res / max(dof, 1)
    residual_std = np.sqrt(sigma2)

    try:
        from scipy.linalg import solve_triangular
        R_inv = solve_triangular(R, np.eye(R.shape[0]))
    except (np.linalg.LinAlgError, Exception):
        R_inv = np.linalg.pinv(R)
    var_beta_scaled = sigma2 * (R_inv @ R_inv.T)
    se_scaled = np.sqrt(np.maximum(np.diag(var_beta_scaled), 0.0))
    se_scaled_coefs = se_scaled[1:]

    coefs_natural = coefs_scaled / x_std
    se_natural = se_scaled_coefs / x_std
    intercept_natural = intercept_scaled - np.sum(coefs_scaled * x_mean / x_std)

    t_stats = coefs_natural / np.where(se_natural > 1e-15, se_natural, np.nan)
    p_values = 2 * (1 - sp_stats.t.cdf(np.abs(t_stats), df=max(dof, 1)))

    model_stats = {
        "r2": r2,
        "adj_r2": adj_r2,
        "n_obs": n_obs,
        "residual_std": residual_std,
        "coefficients": coefs_natural,
        "intercept": intercept_natural,
        "std_errors": se_natural,
        "t_stats": t_stats,
        "p_values": p_values,
    }

    coef_df = pd.DataFrame(coef_history)
    return results, model_stats, coef_df, latest_selections, final_feature_names


def calculate_oos_r2(results):
    """Calculate out-of-sample R² from rolling one-step-ahead predictions."""
    valid = results.dropna(subset=["predicted", "bond_yield"]).copy()
    if len(valid) < 3:
        return np.nan

    actual = valid["bond_yield"].values
    predicted = valid["predicted"].values

    ss_res = np.sum((actual - predicted) ** 2)
    ss_tot = np.sum((actual - actual.mean()) ** 2)

    if ss_tot < 1e-15:
        return np.nan

    return 1 - ss_res / ss_tot


def calculate_signals(results, threshold, lookback=None):
    """
    Calculate z-scores and trading signals using symmetric thresholds.

    For bond yields:
        - CHEAP: z-score > threshold → yields higher than fair value → bonds cheap → BUY
        - RICH:  z-score < -threshold → yields lower than fair value → bonds rich → SELL
        - NEUTRAL: otherwise
    """
    if lookback is not None:
        rolling_mean = results["residual"].rolling(window=lookback, min_periods=20).mean()
        rolling_std = results["residual"].rolling(window=lookback, min_periods=20).std()
        results["z_score"] = (results["residual"] - rolling_mean) / rolling_std
    else:
        valid = results["residual"].dropna()
        mean_r = valid.mean()
        std_r = valid.std()
        results["z_score"] = (results["residual"] - mean_r) / std_r

    def _signal(z):
        if pd.isna(z):
            return "N/A"
        if z > threshold:
            return "CHEAP"
        if z < -threshold:
            return "RICH"
        return "NEUTRAL"

    results["signal"] = results["z_score"].apply(_signal)
    return results


# ─────────────────────────────────────────────────────────────
# Attribution
# ─────────────────────────────────────────────────────────────
def monthly_attribution(results, coef_df, feature_cols, feature_labels):
    """
    Calculate factor-level contribution to predicted yield changes.

    Uses a fully reconciling decomposition:
      1. Feature Effect: coef_T-1 × (feature_T - feature_T-1)
      2. Model Recalibration: everything else (coef drift + interaction + intercept change)

    Returns a DataFrame sorted by absolute contribution (descending).
    """
    if coef_df is None or coef_df.empty or len(coef_df) < 2:
        return None
    last = coef_df.iloc[-1]
    prev = coef_df.iloc[-2]
    idx_last = int(last["idx"])
    idx_prev = int(prev["idx"])

    pred_last = results["predicted"].iloc[idx_last]
    pred_prev = results["predicted"].iloc[idx_prev]
    if pd.isna(pred_last) or pd.isna(pred_prev):
        return None
    actual_pred_change = pred_last - pred_prev

    attrib_rows = []
    total_feature_effect = 0.0

    for col in feature_cols:
        coef_key = f"coef_{col}"
        if coef_key not in prev or coef_key not in last:
            continue
        coef_prev = prev[coef_key]
        coef_last = last[coef_key]
        if pd.isna(coef_prev) and pd.isna(coef_last):
            continue

        coef_for_attrib = coef_prev if not pd.isna(coef_prev) else 0.0
        feat_change = results[col].iloc[idx_last] - results[col].iloc[idx_prev]
        contribution = coef_for_attrib * feat_change
        total_feature_effect += contribution

        if coef_for_attrib == 0 and feat_change == 0:
            continue

        attrib_rows.append({
            "Factor": feature_labels.get(col, col),
            "Coefficient": coef_for_attrib,
            "Feature Change": feat_change,
            "Contribution (yield, %)": contribution,
            "Contribution (bps)": contribution * 100,
        })

    if not attrib_rows:
        return None

    recalib = actual_pred_change - total_feature_effect
    attrib_rows.append({
        "Factor": "Model Recalibration",
        "Coefficient": np.nan,
        "Feature Change": np.nan,
        "Contribution (yield, %)": recalib,
        "Contribution (bps)": recalib * 100,
    })

    attrib = pd.DataFrame(attrib_rows)
    attrib = attrib.sort_values("Contribution (bps)", key=abs, ascending=False).reset_index(drop=True)
    total = attrib["Contribution (yield, %)"].sum()
    attrib["% of Total"] = np.where(abs(total) > 1e-10, attrib["Contribution (yield, %)"] / abs(total) * 100, 0)
    return attrib


# ─────────────────────────────────────────────────────────────
# Charts
# ─────────────────────────────────────────────────────────────
def chart_actual_vs_predicted(results, country):
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=results["date"], y=results["bond_yield"],
                             name=f"Actual {country} Yield", line=dict(color="#2980b9", width=2)))
    fig.add_trace(go.Scatter(x=results["date"], y=results["predicted"],
                             name=f"Predicted {country} Yield", line=dict(color="#e67e22", width=2, dash="dash")))
    fig.update_layout(title=f"Actual vs Predicted {country} Yield",
                      xaxis_title="Date", yaxis_title="Yield (%)",
                      template="plotly_white", height=450, legend=dict(orientation="h", y=1.12))
    return fig


def chart_residuals(results, threshold, lookback=None):
    valid = results.dropna(subset=["residual"]).copy()

    if lookback is not None:
        rolling_mean = valid["residual"].rolling(window=lookback, min_periods=20).mean()
        rolling_std = valid["residual"].rolling(window=lookback, min_periods=20).std()
    else:
        rolling_mean = valid["residual"].expanding(min_periods=20).mean()
        rolling_std = valid["residual"].expanding(min_periods=20).std()

    cheap_band = rolling_mean + threshold * rolling_std
    rich_band = rolling_mean - threshold * rolling_std

    fig = go.Figure()
    colors = valid["signal"].map({"CHEAP": "#e74c3c", "RICH": "#27ae60", "NEUTRAL": "#95a5a6", "N/A": "#bdc3c7"})
    fig.add_trace(go.Scatter(x=valid["date"], y=valid["residual"], mode="lines+markers",
                             marker=dict(color=colors, size=5), line=dict(color="#7f8c8d", width=1),
                             name="Residual"))
    fig.add_trace(go.Scatter(x=valid["date"], y=cheap_band, mode="lines",
                             line=dict(color="#e74c3c", width=1.5, dash="dash"),
                             name=f"Cheap ({threshold}σ)"))
    fig.add_trace(go.Scatter(x=valid["date"], y=rich_band, mode="lines",
                             line=dict(color="#27ae60", width=1.5, dash="dash"),
                             name=f"Rich (-{threshold}σ)"))
    fig.add_trace(go.Scatter(x=valid["date"], y=rolling_mean, mode="lines",
                             line=dict(color="gray", width=1, dash="dot"),
                             name="Rolling Mean"))
    fig.update_layout(title="Residuals Over Time", xaxis_title="Date", yaxis_title="Residual (%)",
                      template="plotly_white", height=400,
                      legend=dict(orientation="h", y=1.12))
    return fig


def chart_zscore(results, threshold):
    valid = results.dropna(subset=["z_score"])
    fig = go.Figure()
    colors = valid["signal"].map({"CHEAP": "#e74c3c", "RICH": "#27ae60", "NEUTRAL": "#95a5a6", "N/A": "#bdc3c7"})
    fig.add_trace(go.Bar(x=valid["date"], y=valid["z_score"],
                         marker_color=colors, name="Z-Score"))
    fig.add_hline(y=threshold, line_dash="dash", line_color="#e74c3c",
                  annotation_text=f"Cheap ({threshold}σ)")
    fig.add_hline(y=-threshold, line_dash="dash", line_color="#27ae60",
                  annotation_text=f"Rich (-{threshold}σ)")
    fig.add_hline(y=0, line_dash="dot", line_color="gray")
    fig.update_layout(title="Z-Score History", xaxis_title="Date", yaxis_title="Z-Score",
                      template="plotly_white", height=400)
    return fig


def chart_coefficients(model_stats, feature_cols, feature_labels):
    labels = [feature_labels.get(c, c) for c in feature_cols]
    coefs = model_stats["coefficients"]
    colors = ["#27ae60" if c >= 0 else "#e74c3c" for c in coefs]
    n_features = len(labels)
    bar_height = max(25, 400 / max(n_features, 1))
    chart_height = max(350, int(n_features * bar_height) + 100)

    fig = go.Figure(go.Bar(
        x=coefs, y=labels, orientation="h",
        marker_color=colors, text=[f"{c:.4f}" for c in coefs],
        textposition="auto",
    ))
    fig.update_layout(title="Factor Coefficients (Latest Window)",
                      xaxis_title="Coefficient Value", yaxis_title="",
                      template="plotly_white", height=chart_height,
                      yaxis=dict(autorange="reversed"))
    return fig


# ─────────────────────────────────────────────────────────────
# Excel Report
# ─────────────────────────────────────────────────────────────
def generate_excel_report(results, model_stats, raw_df, feat_df, attrib_df,
                          feature_cols, feature_labels, variable_flags, original_names,
                          country):
    """Generate a multi-sheet Excel workbook."""
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
        from openpyxl.utils.dataframe import dataframe_to_rows
    except ImportError:
        st.error("openpyxl not installed.")
        return None

    wb = Workbook()

    header_font = Font(bold=True, color="FFFFFF", size=11)
    header_fill = PatternFill(start_color="2C3E50", end_color="2C3E50", fill_type="solid")
    green_fill = PatternFill(start_color="27AE60", end_color="27AE60", fill_type="solid")
    red_fill = PatternFill(start_color="E74C3C", end_color="E74C3C", fill_type="solid")
    gray_fill = PatternFill(start_color="95A5A6", end_color="95A5A6", fill_type="solid")
    thin_border = Border(
        left=Side(style='thin'), right=Side(style='thin'),
        top=Side(style='thin'), bottom=Side(style='thin')
    )

    def _style_header(ws, ncols):
        for col in range(1, ncols + 1):
            cell = ws.cell(row=1, column=col)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = Alignment(horizontal="center")
            cell.border = thin_border

    def _auto_width(ws):
        from openpyxl.utils import get_column_letter
        for col_idx in range(1, ws.max_column + 1):
            max_len = 0
            for row_idx in range(1, ws.max_row + 1):
                cell = ws.cell(row=row_idx, column=col_idx)
                try:
                    max_len = max(max_len, len(str(cell.value or "")))
                except:
                    pass
            col_letter = get_column_letter(col_idx)
            ws.column_dimensions[col_letter].width = min(max_len + 3, 30)

    # --- Sheet 1: Dashboard ---
    ws = wb.active
    ws.title = "Dashboard"
    latest = results.dropna(subset=["z_score"]).iloc[-1]
    ws.append([f"{country} Bond Yield Rich/Cheap Model — Dashboard"])
    ws.merge_cells("A1:D1")
    ws["A1"].font = Font(bold=True, size=16)
    ws.append([])
    ws.append(["Generated", datetime.now().strftime("%Y-%m-%d %H:%M")])
    ws.append(["Latest Data Date", latest["date"].strftime("%Y-%m-%d")])
    ws.append([])
    ws.append(["CURRENT SIGNAL", latest["signal"]])
    sig_cell = ws.cell(row=6, column=2)
    sig_cell.font = Font(bold=True, color="FFFFFF", size=14)
    if latest["signal"] == "CHEAP":
        sig_cell.fill = red_fill
    elif latest["signal"] == "RICH":
        sig_cell.fill = green_fill
    else:
        sig_cell.fill = gray_fill
    ws.append([])
    ws.append(["Metric", "Value"])
    metrics = [
        (f"Actual {country} Yield", f"{latest['bond_yield']:.2f}%"),
        ("Predicted Yield", f"{latest['predicted']:.2f}%"),
        ("Residual", f"{latest['residual']:.2f}%"),
        ("Z-Score", f"{latest['z_score']:.2f}"),
        ("R²", f"{model_stats['r2']:.4f}"),
        ("Adj R²", f"{model_stats['adj_r2']:.4f}"),
        ("Features Used", str(len(feature_cols))),
    ]
    for label, val in metrics:
        ws.append([label, val])
    _auto_width(ws)

    # --- Sheet 2: Data Input ---
    ws2 = wb.create_sheet("Data Input")
    raw_export = raw_df.copy()
    raw_export["date"] = raw_export["date"].dt.strftime("%Y-%m-%d")
    for r in dataframe_to_rows(raw_export, index=False, header=True):
        ws2.append(r)
    _style_header(ws2, len(raw_export.columns))
    _auto_width(ws2)

    # --- Sheet 3: Calculated Features ---
    ws3 = wb.create_sheet("Calculated Features")
    feat_export = feat_df.copy()
    feat_export["date"] = feat_export["date"].dt.strftime("%Y-%m-%d")
    for r in dataframe_to_rows(feat_export, index=False, header=True):
        ws3.append(r)
    _style_header(ws3, len(feat_export.columns))
    _auto_width(ws3)

    # --- Sheet 4: Model Statistics ---
    ws4 = wb.create_sheet("Model Statistics")
    ws4.append(["Feature", "Coefficient", "Std Error", "T-Statistic", "P-Value"])
    _style_header(ws4, 5)
    for i, col in enumerate(feature_cols):
        ws4.append([
            feature_labels.get(col, col),
            round(float(model_stats["coefficients"][i]), 6),
            round(float(model_stats["std_errors"][i]), 6),
            round(float(model_stats["t_stats"][i]), 4),
            round(float(model_stats["p_values"][i]), 6),
        ])
    ws4.append([])
    ws4.append(["Intercept", round(float(model_stats["intercept"]), 6)])
    ws4.append(["R²", round(float(model_stats["r2"]), 6)])
    ws4.append(["Adjusted R²", round(float(model_stats["adj_r2"]), 6)])
    ws4.append(["Observations", int(model_stats["n_obs"])])
    ws4.append(["Residual Std Dev", round(float(model_stats["residual_std"]), 6)])
    _auto_width(ws4)

    # --- Sheet 5: Variable Configuration ---
    ws_vars = wb.create_sheet("Variable Config")
    ws_vars.append(["Variable", "Flag", "Derived Features"])
    _style_header(ws_vars, 3)
    for var, flag in variable_flags.items():
        display = original_names.get(var, var)
        desc = FLAG_DESCRIPTIONS.get(flag, flag)
        ws_vars.append([display, flag, desc])
    _auto_width(ws_vars)

    # --- Sheet 6: Historical Signals ---
    ws5 = wb.create_sheet("Historical Signals")
    hist = results.dropna(subset=["predicted"])[["date", "bond_yield", "predicted", "residual", "z_score", "signal"]].copy()
    hist["date"] = hist["date"].dt.strftime("%Y-%m-%d")
    hist.columns = ["Date", "Yield", "Predicted", "Residual", "Z-Score", "Signal"]
    for r in dataframe_to_rows(hist, index=False, header=True):
        ws5.append(r)
    _style_header(ws5, 6)
    for row in range(2, ws5.max_row + 1):
        sig = ws5.cell(row=row, column=6).value
        if sig == "CHEAP":
            ws5.cell(row=row, column=6).fill = PatternFill(start_color="FFCDD2", fill_type="solid")
        elif sig == "RICH":
            ws5.cell(row=row, column=6).fill = PatternFill(start_color="C8E6C9", fill_type="solid")
    _auto_width(ws5)

    # --- Sheet 7: Instructions ---
    ws6 = wb.create_sheet("Instructions")
    instructions = [
        [f"{country} Bond Yield Rich/Cheap Model"],
        [""],
        ["This model uses rolling multiple linear regression to predict government bond yields"],
        ["based on user-configured market factors with dynamic feature engineering."],
        [""],
        ["Feature Flags (Row 2 of input file):"],
        ["L = Level only"],
        ["LM = Level + Month-over-Month Change"],
        ["LMP = Level + Month-over-Month Change + Percentage Change"],
        ["MP = Month-over-Month Change + Percentage Change"],
        ["P = Percentage Change only"],
        ["N = Exclude variable from model"],
        [""],
        ["Key Concepts:"],
        ["- Predicted Yield: the model's 'fair value' estimate for bond yields"],
        ["- Residual: Actual minus Predicted (positive = yields higher than expected)"],
        ["- Z-Score: standardized residual (how many standard deviations from average)"],
        [""],
        ["Signals:"],
        ["- CHEAP: Z-Score above threshold — yields are higher than expected"],
        ["  (bonds are cheap → potential buying opportunity)"],
        ["- RICH: Z-Score below negative threshold — yields are lower than expected"],
        ["  (bonds are rich → potential selling/hedging opportunity)"],
        ["- NEUTRAL: Z-Score between thresholds — no strong signal"],
        [""],
        ["Symmetric Thresholds:"],
        ["This model uses symmetric thresholds — the same magnitude for RICH and CHEAP."],
    ]
    for row in instructions:
        ws6.append(row)
    ws6["A1"].font = Font(bold=True, size=14)
    _auto_width(ws6)

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf


# ─────────────────────────────────────────────────────────────
# Streamlit App
# ─────────────────────────────────────────────────────────────
def main():
    # ── Sidebar ──
    st.sidebar.image("https://img.icons8.com/color/96/combo-chart.png", width=60)
    st.sidebar.title("Bond Yield Model")
    st.sidebar.markdown("---")

    uploaded_file = st.sidebar.file_uploader(
        "📁 Upload Excel Data",
        type=["xlsx"],
        help="Upload a .xlsx file with Row 1 = headers, Row 2 = feature flags, Row 3+ = data. "
             "Include both 'US 10Y Yield' and 'AU 10Y Yield' columns."
    )

    st.sidebar.markdown("### 🌏 Country Selection")
    country = st.sidebar.radio(
        "Select Bond Market",
        options=["US 10Y", "AU 10Y"],
        index=0,
        help="Choose which country's 10Y yield to model. The other country's yield "
             "can be used as an independent variable (controlled by its flag)."
    )

    st.sidebar.markdown("### ⚙️ Model Settings")
    model_mode = st.sidebar.radio(
        "Model Specification",
        options=["Standard (flag-based)", "Change-on-Change"],
        index=0,
        help="**Standard:** Yield *level* as dependent variable. Independent variables "
             "use transformations from your Row 2 flags.\n\n"
             "**Change-on-Change:** ΔYield (monthly change) as dependent variable. "
             "All level terms dropped; all variables use MoM changes."
    )
    use_changes = model_mode == "Change-on-Change"

    lookback = st.sidebar.select_slider(
        "Lookback Period (months)",
        options=[36, 48, 60],
        value=60,
        help="Number of months used in the rolling regression window."
    )
    threshold = st.sidebar.slider(
        "Signal Threshold (σ)", 0.5, 3.0, 1.5, 0.1,
        help="Symmetric threshold: Z-score above this → CHEAP (yields too high); "
             "Z-score below negative → RICH (yields too low)."
    )

    st.sidebar.markdown("---")

    # ── Main Panel ──
    st.title(f"📊 {country} Bond Yield — Rich/Cheap Model")
    if use_changes:
        st.caption("⚡ **Change-on-Change mode** — regressing ΔYield on Δ(variables). "
                   "Level terms dropped; all variables use MoM changes.")

    if uploaded_file is None:
        st.info("👈 Upload your Excel data file in the sidebar to get started.")
        with st.expander("ℹ️ About This Model"):
            st.markdown("""
            This tool runs a **rolling multiple linear regression** to estimate the "fair value"
            of government bond yields based on market factors you define.

            **Multi-Country Support:** Include both US 10Y Yield and AU 10Y Yield columns
            in your Excel file. Toggle between countries using the sidebar.

            **Dynamic Variable Support:** The model accepts any number of independent variables.
            Use Row 2 of your Excel file to control how each variable is transformed:

            | Flag | Features Generated |
            |------|--------------------|
            | `L`  | Level only |
            | `LM` | Level + Month-over-Month Change |
            | `LMP`| Level + MoM Change + % Change |
            | `MP` | MoM Change + % Change |
            | `P`  | % Change only |
            | `N`  | Exclude from model |

            **Signal Interpretation (bonds):**
            - **CHEAP:** Yields are *higher* than the model's fair value → bonds are undervalued → BUY
            - **RICH:** Yields are *lower* than the model's fair value → bonds are overvalued → SELL/HEDGE
            """)
        return

    # Load data
    result = load_data(uploaded_file, country)
    if result[0] is None:
        return
    raw_df, dep_var_col, variable_flags, original_names = result

    # Show detected configuration in sidebar
    st.sidebar.markdown("---")
    st.sidebar.markdown("### 📋 Detected Variables")
    st.sidebar.markdown(f"**Dependent:** {dep_var_col}")
    active_count = sum(1 for f in variable_flags.values() if f != "N")
    excluded_count = sum(1 for f in variable_flags.values() if f == "N")
    st.sidebar.markdown(f"**Independent:** {active_count} active, {excluded_count} excluded")
    with st.sidebar.expander("Variable Details", expanded=False):
        for var, flag in variable_flags.items():
            display = original_names.get(var, var)
            icon = "🟢" if flag != "N" else "🔴"
            st.markdown(f"{icon} **{display}** → `{flag}` ({FLAG_DESCRIPTIONS.get(flag, flag)})")

    # Feature engineering
    feat_df, feature_cols, feature_labels, competing_pairs = engineer_features(
        raw_df, variable_flags, original_names, change_on_change=use_changes
    )

    if len(feature_cols) == 0:
        st.error("❌ No features were generated. Check your feature flags.")
        return

    if len(feat_df) < lookback + 5:
        st.error(f"Not enough data ({len(feat_df)} rows after feature engineering) for {lookback}-month lookback.")
        return

    # Run model
    with st.spinner("Running rolling regression..."):
        reg_result = run_regression(feat_df, feature_cols, lookback, competing_pairs)

    if reg_result is None or reg_result[0] is None:
        return

    results, model_stats, coef_df, latest_selections, active_feature_cols = reg_result
    results = calculate_signals(results, threshold, lookback)

    active_feature_labels = {c: feature_labels.get(c, c) for c in active_feature_cols}

    # ── Sidebar: Feature selection info ──
    if competing_pairs:
        st.sidebar.markdown("---")
        st.sidebar.markdown("### 🔀 Feature Selection")
        st.sidebar.caption("Per-window auto-selection (latest window):")
        for mom_col, pct_col, var in competing_pairs:
            display_name = original_names.get(var, var)
            sel = latest_selections.get(var, "mom")
            if sel == "pct":
                st.sidebar.markdown(f"**{display_name}:** % Change selected *(MoM dropped)*")
            else:
                st.sidebar.markdown(f"**{display_name}:** MoM Change selected *(% dropped)*")

    # ── Sidebar: Coefficient summary ──
    st.sidebar.markdown("---")
    st.sidebar.markdown("### 📊 Coefficients (Latest Window)")
    for i, col in enumerate(active_feature_cols):
        label = active_feature_labels.get(col, col)
        coef_val = model_stats["coefficients"][i]
        sign = "+" if coef_val >= 0 else ""
        st.sidebar.markdown(f"**{label}:** `{sign}{coef_val:.4f}`")

    # ── Section 1: Current Signal ──
    latest = results.dropna(subset=["z_score"]).iloc[-1]
    prev_rows = results.dropna(subset=["z_score"])
    prev_signal = prev_rows.iloc[-2]["signal"] if len(prev_rows) >= 2 else "N/A"

    signal = latest["signal"]
    # For bonds: CHEAP = yields too high (red — sell-off), RICH = yields too low (green — rally)
    css_class = {"CHEAP": "signal-cheap", "RICH": "signal-rich"}.get(signal, "signal-neutral")
    st.markdown(f"""
    <div class="signal-box {css_class}">
        <div style="font-size:14px; opacity:0.85;">Current Signal as of {latest['date'].strftime('%B %d, %Y')}</div>
        <div style="font-size:42px; margin:8px 0;">{signal}</div>
        <div style="font-size:18px;">Z-Score: {latest['z_score']:.2f}</div>
    </div>
    """, unsafe_allow_html=True)

    # ── Section 2: Key Metrics ──
    oos_r2 = calculate_oos_r2(results)

    col1, col2, col3, col4 = st.columns(4)
    if use_changes:
        col1.metric(f"Actual Δ{country} Yield", f"{latest['bond_yield']:+.2f}%")
        col2.metric("Predicted ΔYield", f"{latest['predicted']:+.2f}%")
    else:
        col1.metric(f"Actual {country} Yield", f"{latest['bond_yield']:.2f}%")
        col2.metric("Predicted Yield", f"{latest['predicted']:.2f}%")
    col3.metric("Residual", f"{latest['residual']:+.2f}%")
    col4.metric("In-Sample R²", f"{model_stats['r2']:.3f}")

    col5, col6, col7, col8 = st.columns(4)
    col5.metric("Z-Score", f"{latest['z_score']:+.2f}")
    col6.metric("Signal", signal)
    col7.metric("OOS R²", f"{oos_r2:.3f}" if not np.isnan(oos_r2) else "N/A",
                help="Out-of-sample R² from rolling one-step-ahead predictions.")
    col8.metric("Adj. R²", f"{model_stats['adj_r2']:.3f}")

    st.markdown("---")

    # ── Section 3: Charts ──
    st.subheader("📈 Interactive Charts")

    tab1, tab2, tab3, tab4 = st.tabs([
        "Actual vs Predicted", "Residuals", "Z-Score History", "Factor Coefficients"
    ])

    with tab1:
        fig_avp = chart_actual_vs_predicted(results, country)
        if use_changes:
            fig_avp.update_layout(title=f"Actual vs Predicted Δ{country} Yield (MoM Change)",
                                  yaxis_title="Yield Change (%)")
        st.plotly_chart(fig_avp, use_container_width=True)
    with tab2:
        st.plotly_chart(chart_residuals(results, threshold, lookback), use_container_width=True)
    with tab3:
        st.plotly_chart(chart_zscore(results, threshold), use_container_width=True)
    with tab4:
        st.plotly_chart(chart_coefficients(model_stats, active_feature_cols, active_feature_labels), use_container_width=True)

    st.markdown("---")

    # ── Section 4: Commentary & Monthly Attribution ──
    st.subheader("📝 Commentary & Attribution")
    attrib = monthly_attribution(results, coef_df, active_feature_cols, active_feature_labels)
    if attrib is not None and len(attrib) > 0:
        net_move = attrib["Contribution (bps)"].sum()

        factor_attrib = attrib[attrib["Factor"] != "Model Recalibration"]
        recalib_row = attrib[attrib["Factor"] == "Model Recalibration"]
        recalib_bps = recalib_row["Contribution (bps)"].iloc[0] if len(recalib_row) > 0 else 0.0

        top = factor_attrib.head(3)

        lines = [
            f"**Net Model Move:** The model's fair-value yield "
            f"moved by **{net_move:+.1f} bps** this month."
        ]

        driver_labels = ["Primary Driver", "Secondary Driver", "Tertiary Driver"]
        for i, label in enumerate(driver_labels):
            if i < len(top):
                row = top.iloc[i]
                lines.append(
                    f"**{label}:** {row['Factor']} "
                    f"({row['Contribution (bps)']:+.1f} bps)"
                )

        if abs(recalib_bps) >= 0.5:
            lines.append(
                f"**Model Recalibration:** {recalib_bps:+.1f} bps "
                f"(coefficient drift + intercept change from rolling window shift)"
            )

        lines.append(
            f"**Signal Status:** Yields are currently **{signal}** "
            f"with a Z-Score of **{latest['z_score']:.2f}** "
            f"(R²: {model_stats['r2']:.3f})."
        )

        st.info("\n\n".join(lines))

        material = attrib[attrib["Contribution (bps)"].abs() >= 0.5].copy()

        with st.expander(f"🔍 Detailed Factor Attribution ({len(material)} material factors)", expanded=False):
            if len(material) > 0:
                def _fmt(val, fmt_str):
                    if pd.isna(val):
                        return "—"
                    return fmt_str.format(val)

                st.dataframe(
                    material[["Factor", "Coefficient", "Feature Change",
                              "Contribution (yield, %)", "Contribution (bps)", "% of Total"]].style.format({
                        "Coefficient": lambda v: _fmt(v, "{:.6f}"),
                        "Feature Change": lambda v: _fmt(v, "{:.4f}"),
                        "Contribution (yield, %)": "{:+.4f}",
                        "Contribution (bps)": "{:+.1f}",
                        "% of Total": "{:+.1f}%",
                    }),
                    use_container_width=True,
                )
            else:
                st.caption("No factors with impact ≥ 0.5 bps this month.")

        noise_count = len(attrib) - len(material)
        if noise_count > 0:
            st.caption(f"ℹ️ {noise_count} factor(s) with < 0.5 bps impact hidden.")
    else:
        st.info("Attribution data not yet available (requires at least 2 regression windows).")

    # ── Section 5: Regression Statistics ──
    with st.expander("📋 Regression Statistics", expanded=False):
        stats_df = pd.DataFrame({
            "Feature": [active_feature_labels.get(c, c) for c in active_feature_cols],
            "Coefficient": model_stats["coefficients"],
            "Std Error": model_stats["std_errors"],
            "T-Statistic": model_stats["t_stats"],
            "P-Value": model_stats["p_values"],
        })
        # Sort by absolute T-Statistic (most significant first)
        stats_df = stats_df.sort_values("T-Statistic", key=abs, ascending=False).reset_index(drop=True)
        st.dataframe(
            stats_df.style.format({
                "Coefficient": "{:.6f}",
                "Std Error": "{:.6f}",
                "T-Statistic": "{:.3f}",
                "P-Value": "{:.4f}",
            }).apply(lambda x: ["background-color: #fff3cd" if v < 0.05 else "" for v in x], subset=["P-Value"]),
            use_container_width=True,
        )

        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Intercept", f"{model_stats['intercept']:.4f}")
        c2.metric("In-Sample R²", f"{model_stats['r2']:.4f}")
        c3.metric("OOS R²", f"{oos_r2:.4f}" if not np.isnan(oos_r2) else "N/A")
        c4.metric("Residual Std", f"{model_stats['residual_std']:.4f}")

        with st.expander("🔧 SE Diagnostics", expanded=False):
            st.markdown(f"**n_obs:** {model_stats['n_obs']}  |  "
                        f"**k (features):** {len(active_feature_cols)}  |  "
                        f"**dof:** {model_stats['n_obs'] - len(active_feature_cols) - 1}")
            st.markdown(f"**Residual Std (σ):** {model_stats['residual_std']:.10f}")
            st.markdown(f"**Std Errors:** {[f'{v:.10f}' for v in model_stats['std_errors']]}")
            st.markdown(f"**Features used:** {active_feature_cols}")

    # ── Section 6: Historical Signals ──
    with st.expander("📅 Historical Signals Table", expanded=False):
        hist = results.dropna(subset=["predicted"])[["date", "bond_yield", "predicted", "residual", "z_score", "signal"]].copy()
        hist.columns = ["Date", "Yield", "Predicted", "Residual", "Z-Score", "Signal"]

        def _color_signal(val):
            if val == "CHEAP":
                return "background-color: #ffcdd2; color: #b71c1c;"
            elif val == "RICH":
                return "background-color: #c8e6c9; color: #1b5e20;"
            return ""

        st.dataframe(
            hist.style.format({
                "Date": lambda x: x.strftime("%Y-%m-%d"),
                "Yield": "{:.2f}",
                "Predicted": "{:.2f}",
                "Residual": "{:+.3f}",
                "Z-Score": "{:+.2f}",
            }).map(_color_signal, subset=["Signal"]),
            use_container_width=True,
            height=400,
        )

    # ── Excel Download ──
    st.markdown("---")
    attrib = monthly_attribution(results, coef_df, active_feature_cols, active_feature_labels)
    excel_buf = generate_excel_report(
        results, model_stats, raw_df, feat_df, attrib,
        active_feature_cols, active_feature_labels, variable_flags, original_names,
        country
    )
    if excel_buf:
        country_short = country.replace(" ", "_")
        st.download_button(
            "📥 Download Excel Report",
            data=excel_buf,
            file_name=f"{country_short}_BondYield_Report_{datetime.now().strftime('%Y%m%d')}.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.ml.sheet",
        )


if __name__ == "__main__":
    main()
